language: ruby

rvm: 2.3.3

cache: bundler

sudo: false

env:
  global:
  - secure: JoDmNlGFNERpWd/KipsTTscRD/ZKmZhIUMfpHIqYbhmCpWkewTXZaJ97ZA1c1qj/SiOY1rOK/RlBI+0zeMT9z5sVDmoGpWHsg/VIlsWzcQjPfbG3gESg5pWEcz2l0BBrXG4aphc0jAAj3ipICSGS2BSLF9LegSJG+fYBZvqpcHunThd1CA1QQP0R90Q0lyMSfa0B7NrXa3wU7kFaA3yYr2P5HTGn964ZIC7L6z4+P7Y6MjWhzroqmhYEMvYeFhjT7wnEu8bOgXJPxm/HOYgdFrD/QEoDE9DlmZK9tZGFuYMV9lT/GYFwqQlS5Kp6H0BMYpAoVAZbv6hdJQkIdEzbSXcON3zHoqBjhtZ6uSfmyfoc9k6KGPJz8apD+ZJH+EHyzSDY4xI7pKoVl/6EaviToO955VgbDFKOH9N6g6xJFZvNJX31DFdRTjrpefyeLWmCt0cqk9jQT8LMduEC578KQzB9WqJw5uvuNtPaK6UUXN/DmAoGetCRWg2jCrb80qi7GAOop/1GqKQCO0X7My2O4q4r4ZETW72VPFFK7esWSMUfYMLz7SnGq3g0O5AFIwz48tMRzmu4RwWjiUxJ9m33jRtKzciZnLpc/VGFaCXkJV/G1T23AcFOr+GF2tjWRhziiwc5bHtZqXAeaUpGfu9kqar8y7qQ/1qQIvDbfaJom0k=

notifications:
  email: false

branches:
  only:
  - master

before_script:
- chmod +x ./scripts/build.sh
- chmod +x ./scripts/deploy.sh

script: "./scripts/build.sh"

after_success: "./scripts/deploy.sh"
