# Configuration
# https://jekyllrb.com/docs/configuration/

# General
repository: DECAF/blog.decaf.de
timezone: Europe/Berlin
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"
url: https://blog.decaf.de

# Optional plugins
# https://help.github.com/articles/configuring-jekyll-plugins/#optional-plugins
plugins:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-avatar
- jemoji
- jekyll-mentions

# SEO
# https://github.com/jekyll/jekyll-seo-tag
title: DECAF Blog
description: "Web-driven software company based in Berlin and Langenberg/NRW, Germany: Design/UX, Laravel + React."
keywords: wait, what?

# Collections
# https://jekyllrb.com/docs/collections/
collections:
  authors:
    output: true
    permalink: /author/:name/
    layout: "page"

# Assets
# https://jekyllrb.com/docs/assets/
sass:
  style: compressed

# Exclude directories and/or files from the conversion.
# https://jekyllrb.com/docs/configuration/
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- SETUP.md
- scripts
- CNAME
